services:

  mariadb:
    image: linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      PUID: 1000
      PGID: 100
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: teste123
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: teste123

    volumes:
      - /docker/NextcloudServer/mariadb/config:/config
      - /docker/NextcloudServer/mariadb/data:/var/lib/data
    networks:
      - nextcloud_ntw
    ports:
      - 3306:3306
    restart: unless-stopped

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      PUID: 1000
      PGID: 100
      TZ: America/Sao_Paulo
    volumes:
      - /docker/NextcloudServer/nextcloud/config:/config
      - /docker/NextcloudServer/nextcloud/data:/data
    networks:
      - nextcloud_ntw
    ports:
      - 443:443
    depends_on:
      - mariadb
    links:
      - mariadb
    restart: unless-stopped
networks:
  nextcloud_ntw:
    driver: bridge
